" Formatting, indentation, etc.
set nocompatible
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set ruler
set incsearch
set backspace=indent,eol,start
set expandtab

" In certain files do not let a # character move to first column.
autocmd BufRead *.txt inoremap # X<c-h>#

" Make <space> in normal mode go down a page rather than left a character.
noremap <space> <C-f>

" Map navigation between windows.
map cn <esc>:cn<CR>
map cp <esc>:cp<CR>
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
nmap <silent> <A-1> 1gt
nmap <silent> <A-2> 2gt
nmap <silent> <A-3> 3gt
nmap <silent> <A-4> 4gt
nmap <silent> <A-5> 5gt
nmap <silent> <A-6> 6gt
nmap <silent> <A-7> 7gt
nmap <silent> <A-8> 8gt
nmap <silent> <A-9> 9gt

" Turn off audible and visual error bells.
set noerrorbells
set vb t_vb=""
autocmd VimEnter * set vb t_vb=

" Appearance.
set guifont=Andale\ Mono\ 7
colorscheme default
" Remove menu.
set guioptions-=m
" Remove right sCRoll bar.
set guioptions-=r
" Remove left sCRoll bar.
set guioptions-=l
" Remove toolbar.
set guioptions-=T

" Ctags support.
let g:ctags_statusline=1

" Show the current function name in the status bar. Use <f>.
fun! ShowFuncName()
  let lnum = line(".")
  let col = col(".")
  echohl ModeMsg
  echo getline(search("^[^ \t#/]\\{2}.*[^:]\s*$", 'bW'))
  echohl None
  call search("\\%" . lnum . "l" . "\\%" . col . "c")
endfun
map f :call ShowFuncName() <CR>

" Sort words in a visual selection alphabetically.
:vnoremap <F2> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>
:vnoremap <C-\> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>

" Automatically call astyle to format code when opening a file.
" Note that Artistic Style must be installed. Use <gg><gqG>
" for entire file or <gq][> from the top of a function to
" only format a function.
"autocmd BufNewFile,BufRead *.cc set formatprg=astyle\ -bpHUs2
:nnoremap <silent> <F3> :formatprg=astyle\ -bpHUs2<CR>
:nnoremap <silent> <F4> gggqG

" Remove Windows line endings.
map <F5> :%s/\r$//

" Remove trailing whitespace.
:nnoremap <silent> <F6> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

" Condense multiple empty lines into a single empty line.
:nnoremap <silent> <F7> :%s/\n\{3,}/\r\r/e<CR>

" Toggle spell checking in the current buffer.
" Use zg to add word under cursor to dictionary.
map <F8> :setlocal spell! spelllang=en<CR>

" Find fprintf NOT preceded by comment.
:nnoremap <silent> <F9> /\(\/\/.*\)\@<!fprintf<CR>

" Use CMake syntax highlighting for more than just default filenames.
au BufNewFile,BufRead *.urdf set filetype=xml
au BufNewFile,BufRead *.launch set filetype=xml
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au BufNewFile,BufFilePre,BufRead *.js set filetype=javascript
filetype plugin on

" Use different number of spaces per tab based on filename extension.
set ts=2 sts=2 sw=2
autocmd Filetype python setlocal ts=4 sts=4 sw=4

" Place a vertical bar in the specified column.
set colorcolumn=120
au FileType python setlocal colorcolumn=80
"match ErrorMsg '\%>120v.\+'

" Vundle (https://github.com/VundleVim/Vundle.vim)
"set nocompatible
"filetype off
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"Plugin 'VundleVim/Vundle.vim'
"Plugin 'taketwo/vim-ros'
"Plugin 'scrooloose/syntastic'
"call vundle#end()
"filetype plugin indent on
"let g:ycm_semantic_triggers = {
"      \ 'roslaunch' : ['="', '$(', '/'],
"      \ 'rosmsg,rossrv,rosaction' : ['re!^', '/'],
"      \ }

" Vim-plug (https://github.com/junegunn/vim-plug)
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/taketwo/vim-ros'
Plug 'https://github.com/scrooloose/syntastic'
Plug 'https://github.com/scrooloose/nerdtree'
Plug 'https://github.com/vim-airline/vim-airline'
Plug 'https://github.com/tpope/vim-fugitive'
call plug#end()

" NERDTree configuration
" 2 lines for showing at startup if no files specified
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Pathogen (https://github.com/tpope/vim-pathogen)
execute pathogen#infect()

" Syntastic (https://github.com/scrooloose/syntastic)
let g:syntastic_always_populate_loc_list = 1
let g:javascript_plugin_jsdoc = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_enable_signs = 1
" let g:syntastic_auto_loc_list = 2
" let g:syntastic_cpp_check_header = 1
" let g:syntastic_cpp_no_include_search = 0
" let g:syntastic_cpp_compiler = "g++"
" let g:syntastic_error_symbol = "X"
" let g:syntastic_style_error_symbol = ">"
" let g:syntastic_warning_symbol = "!"
" let g:syntastic_style_warning_symbol = ">"
