" Vim-plug (https://github.com/junegunn/vim-plug)
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/taketwo/vim-ros'
Plug 'https://github.com/scrooloose/syntastic'
Plug 'https://github.com/scrooloose/nerdtree'
Plug 'https://github.com/vim-airline/vim-airline'
Plug 'https://github.com/vim-airline/vim-airline-themes'
Plug 'https://github.com/tpope/vim-fugitive'
"Plug 'https://github.com/nvie/vim-flake8'
"Plug 'https://github.com/Rip-Rip/clang_complete'
Plug 'https://github.com/suan/vim-instant-markdown'
Plug 'https://github.com/rhysd/vim-clang-format'
Plug 'https://github.com/Shutnik/jshint2.vim'
call plug#end()

set laststatus=2 " Allows vim-airline to show up with single file open

" NERDTree configuration
" 2 lines for showing at startup if no files specified
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Flake8
autocmd FileType python map <buffer> <F3> :call Flake8()<CR>

" Syntastic (https://github.com/scrooloose/syntastic)
let g:syntastic_always_populate_loc_list = 1
let g:javascript_plugin_jsdoc = 1
let g:syntastic_python_checkers = ['pylint', 'pep8', 'pep257', 'pylama', 'pyflakes', 'frosted', 'mypy', 'prospector', 'pycodestyle', 'python']

" Instant Markdown
let g:instant_markdown_slow = 1

" Sort words in a visual selection alphabetically.
:vnoremap <F2> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>
:vnoremap <C-\> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>

" Remove trailing whitespace.
:nnoremap <silent> <F6> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

" Condense multiple empty lines into a single empty line.
:nnoremap <silent> <F7> :%s/\n\{3,}/\r\r/e<CR>

" Toggle spell checking in the current buffer.
" Use zg to add word under cursor to dictionary.
map <F8> :setlocal spell! spelllang=en<CR>

" Formatting, indentation, etc.
set nocompatible
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set ruler
set incsearch
set backspace=indent,eol,start
set expandtab

" In certain files do not let a # character move to first column.
autocmd BufRead *.txt inoremap # X<c-h>#

" Make <space> in normal mode go down a page rather than left a character.
noremap <space> <C-f>

" Map navigation between windows.
map cn <esc>:cn<CR>
map cp <esc>:cp<CR>
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

" Appearance.
set guifont=Andale\ Mono\ 9
colorscheme default
set guioptions-=m " Remove menu.
set guioptions-=r " Remove right sCRoll bar.
set guioptions-=l " Remove left sCRoll bar.
set guioptions-=T " Remove toolbar.

" Ctags support.
let g:ctags_statusline=1

" Show the current function name in the status bar. Use <f>.
fun! ShowFuncName()
  let lnum = line(".")
  let col = col(".")
  echohl ModeMsg
  echo getline(search("^[^ \t#/]\\{2}.*[^:]\s*$", 'bW'))
  echohl None
  call search("\\%" . lnum . "l" . "\\%" . col . "c")
endfun
map f :call ShowFuncName() <CR>

" Syntax highlighting for more than just default filenames.
au BufNewFile,BufRead *.urdf set filetype=xml
au BufNewFile,BufRead *.launch set filetype=xml
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au BufNewFile,BufFilePre,BufRead *.js set filetype=javascript
filetype plugin on

" Use different number of spaces per tab based on filename extension.
set ts=2 sts=2 sw=2
autocmd Filetype python setlocal ts=4 sts=4 sw=4

" Place a vertical bar in the specified column.
set colorcolumn=120
au FileType python setlocal colorcolumn=80
au FileType markdown setlocal colorcolumn=120
"match ErrorMsg '\%>120v.\+'

" Turn off audible and visual error bells.
set noerrorbells
set vb t_vb=""
autocmd VimEnter * set vb t_vb=
